name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "yarn"
            - run: corepack enable
            - run: corepack prepare yarn@1.22.19 --activate
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            # - run: yarn typecheck
            - run: yarn test --ci
            - run: yarn build

    deploy:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        needs: validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Heroku CLI
              run: curl https://cli-assets.heroku.com/install.sh | sh

            - name: Log in to Heroku Container Registry
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                  echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

            - name: Build Docker Image with Env Var
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              run: |
                  docker build \
                    --build-arg OPENAI_API_KEY=${OPENAI_API_KEY} \
                    -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

            - name: Push Docker Image to Heroku
              run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

            - name: Release Heroku App
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                  IMAGE_ID=$(docker inspect registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web --format={{.Id}})
                  curl -n -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
                    -d '{ "updates": [ { "type": "web", "docker_image": "'"$IMAGE_ID"'" } ] }' \
                    -H "Content-Type: application/json" \
                    -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
                    -H "Authorization: Bearer $HEROKU_API_KEY"
